- name: Create Azure Ubuntu 18.04 LTS VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create Public IP address
    azure_rm_publicipaddress:
      resource_group: LinuxEnvironment
      allocation_method: Static
      name: WebServer001VM-ip
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: LinuxEnvironment
      name: WebServer001-nsg
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 101
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 443
          access: Allow
          priority: 102
          direction: Inbound
  - name: Create Virtual Network Interface Card
    azure_rm_networkinterface:
      resource_group: LinuxEnvironment
      name: WebServer001NIC
      virtual_network: Linux-VNET
      subnet: default
      public_ip_name:
      security_group: WebServer001-nsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: LinuxEnvironment
      name: WebServer001
      vm_size: Standard_D2S_v3
      admin_username: soumi
      ssh_password_enabled: true
      ssh_password: Passwordmicrosoft@123
      #ssh_public_keys: false
      #  - path: /home/azureuser/.ssh/authorized_keys
      #   key_data: <your-key-data>
      network_interfaces: WebServer001NIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: '18.04.201811010latest'
