- name: Install Apache2
  hosts: all
  remote_user: soumi
  #become_method: sudo
  tasks:
    - name: Install Apache 
      apt: name=apache2 update_cache=yes state=latest
    - name: ensure apache2 service is running
      service: 
        name: "apache2" 
        state: started 
        enabled: yes
      register: apache2_status
    - debug: msg="apache2 service is running"
      when: apache2_status.stdout.find("running") != -1
    - debug: msg="apache2 service is not running"
      when: apache2_status.stdout.find("running") == -1
      