- name: Install Apache2
  hosts: all
  remote_user: soumi
  #become_method: sudo
  tasks:
    - name: Install Apache2 
      apt: name=apache2 update_cache=yes state=latest

    - name: Ensure apache2 service is running
      #sudo: yes
      #command: systemctl status apache2
      #ignore_errors: yes
      #changed_when: false
      service_facts:
      register: services_state
    
    - name: Report apache2 service status
      debug:
        var: services_state
      #fail: 
      #  msg: | 
      #   Service apache2 not running.
      #    Output: 
      #    {{ apache2_service_status.stdout }}
      #    {{ apache2_service_status.stderr }}
      #when: apache2_service_status | falied

    