- name: Install Apache2
  hosts: all
  remote_user: soumi
  #become_method: sudo
  tasks:
    - name: Install Apache2 
      apt: name=apache2 update_cache=yes state=latest

    - name: Ensure apache2 service is running
      service: name=apache2 state=started
      become: yes
      become_method: sudo
    